<<<<<<< HEAD
theme: jekyll-theme-cayman
defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"
=======
theme: jekyll-theme-slate
>>>>>>> 6bb3c94eeac93c99f0fb79ee850a645061189db9
